version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"  # HTTP (optional)
      - "443:443"  # HTTPS
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt  # Mount the SSL certificates
    networks:
      - npm_network

  frontend:
    build:
      context: blessed1dominic/starlight:latest
    container_name: starlight-app
    networks:
      - npm_network

  backend:
    build:
      context: ./flask-app
    container_name: backend-app
    networks:
      - npm_network

networks:
  npm_network:
