version: "3.8"

services:
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    restart: always
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    environment:
      DB_SQLITE_FILE: "/data/database.sqlite"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - npm_network

  frontend:
    build:
      context: ./starlight
    container_name: starlight-app
    ports:
      - "3003:3003"
    networks:
      - npm_network

  backend:
    build:
      context: ./flask-app 
    container_name: backend-app
    ports:
      - "5001:5001" 
    networks:
      - npm_network

networks:
  npm_network:
