name: CI/CD for Frontend (Starlight)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        working-directory: ./starlight
        run: |
          docker build -t blessed1dominic/starlight:${{ github.sha }} .
          docker tag blessed1dominic/starlight:${{ github.sha }} blessed1dominic/starlight:latest

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push Docker Image
        run: |
          docker push blessed1dominic/starlight:${{ github.sha }}
          docker push blessed1dominic/starlight:latest

      - name: SSH into GCP and Deploy Frontend
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.GCP_HOST }}
          username: ubuntu
          key: ${{ secrets.GCP_SSH_KEY }}
          script: |
            # Backup current container (optional)
            docker commit starlight-app starlight-app-backup || true

            # Stop and remove the current container
            docker stop starlight-app || true
            docker rm starlight-app || true

            # Pull the latest image
            docker pull blessed1dominic/starlight:latest

            # Use Docker Compose to start the containers
            
            docker-compose -f ~/docker-curriculum/docker-compose.yml up -d

