name: CI/CD for Frontend (Starlight)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        working-directory: ./starlight
        run: |
          docker build -t blessed1dominic/starlight:${{ github.sha }} .

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push Docker Image
        run: |
          docker push blessed1dominic/starlight:${{ github.sha }}

      - name: SSH into GCP and Deploy Frontend
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.GCP_HOST }}  # Your GCP instance IP or hostname
          username: ubuntu  # Your username on the GCP instance
          key: ${{ secrets.GCP_SSH_KEY }}  # Your SSH private key
          script: |
            # Backup current container (optional)
            docker commit starlight-app starlight-app-backup || true
            # Pull the latest image
            docker pull blessed1dominic/starlight:${{ github.sha }}
            # Stop the current container
            docker stop starlight-app || true
            docker rm starlight-app || true
            # Run the new container
            docker run -d --name starlight-app blessed1dominic/starlight:${{ github.sha }}
